[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\tetsuya\kisaragi\kisaragi-tree\kisaragi-tree-sync.exe
FriendlyName=kisaragi tree sync
AppLaunched=tree-sync.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=tree-sync.cmd
UserQuietInstCmd=tree-sync.cmd
SourceFiles=SourceFiles
[SourceFiles]
SourceFiles0=C:\Users\tetsuya\kisaragi\kisaragi-tree\
[SourceFiles0]
%tree-sync.cmd%=
%tree-sync.ps1%=
[Strings]
tree-sync.cmd=tree-sync.cmd
tree-sync.ps1=tree-sync.ps1
